// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvlerjigrooonicnfpsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2bGVyamlncm9vb25pY25mcHNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzOTU2MDAsImV4cCI6MjA2Mzk3MTYwMH0.E-WCv-6WBOh9_h0eYy5dawyZFFxWO5HKFVdVIlBpejs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);